# Generated by Django 4.1.4 on 2023-01-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IlluvialName', models.CharField(max_length=50)),
                ('IlluvialTier', models.IntegerField(max_length=1)),
                ('IlluvialStage', models.IntegerField(max_length=1)),
                ('ShardTier', models.IntegerField(max_length=1)),
                ('Captured', models.BooleanField()),
                ('RegisterDate', models.CharField(max_length=8)),
            ],
        ),
    ]
