# Generated by Django 4.1.4 on 2023-01-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illuviumsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratesearch',
            name='IlluvialName',
        ),
        migrations.AlterField(
            model_name='ratesearch',
            name='Captured',
            field=models.BooleanField(verbose_name='捕獲成否'),
        ),
        migrations.AlterField(
            model_name='ratesearch',
            name='IlluvialStage',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3)], verbose_name='IlluvialStage'),
        ),
        migrations.AlterField(
            model_name='ratesearch',
            name='IlluvialTier',
            field=models.IntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], verbose_name='IlluvialTier'),
        ),
        migrations.AlterField(
            model_name='ratesearch',
            name='ShardTier',
            field=models.IntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], verbose_name='ShardTier'),
        ),
    ]
