# Generated by Django 4.1.4 on 2023-01-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illuviumsite', '0002_remove_ratesearch_illuvialname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratesearch',
            name='IlluvialStage',
            field=models.IntegerField(verbose_name='IlluvialStage'),
        ),
        migrations.AlterField(
            model_name='ratesearch',
            name='IlluvialTier',
            field=models.IntegerField(verbose_name='IlluvialTier'),
        ),
        migrations.AlterField(
            model_name='ratesearch',
            name='ShardTier',
            field=models.IntegerField(verbose_name='ShardTier'),
        ),
    ]
