# Generated by Django 4.1.4 on 2022-12-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Mail', models.EmailField(max_length=100)),
                ('RegistrationDate', models.DateField()),
            ],
        ),
    ]
