# Generated by Django 4.1.4 on 2023-01-10 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_people_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='Mail',
        ),
    ]
